### PR TITLE
Add MiddlewareRoute

### PR DESCRIPTION
**Pull request by zabojad**
Add externs for [Router creation and Route specific middleware](http://expressjs.com/en/api.html#router).

### CODE REVIEW

**Comment by clemos** [comment]
Great, thanks :)
To follow our convention, it would be better to use `Router.new` instead of a static `Express.Router`.
Also, please PR to `develop` instead of `master`.

**Comment by zabojad** [comment]
"To follow our convention, it would be better to use Router.new instead of a static Express.Router."
=> The original express API exposes a express.Router() function to create a Router instance. Are you sure you prefer a Router.new() constructor method instead ? (Actually, I'm not even sure how it could be translated in haxe extern as it would "move" the Router instanciation from the Express class to the Router class...).

"Also, please PR to develop instead of master."
=> OK, I'll do that as soon as we've sorted out the first point...

**Comment by clemos** [comment]
Yes, `new js.npm.express.Router( options );` should work.
Because of `Router implements npm.Package.RequireNamespace<"express","~4.0">`, it will translate to `new require('express').Router( options )`.
If you really need Haxe to drop the `new`, you can add a `@:selfCall` meta to `Router.new` (see https://github.com/HaxeFoundation/haxe/issues/3441)
But in general, it's not necessary.

**Comment by zabojad** [comment]
done! I'm PR-ing it on develop...

**Pull request closed without merging**
