### PR TITLE
Added "name" parameter to Passport.use method prototype

### PR DESCRIPTION
**Pull request by fantoine**
```passport.use()``` function can be used with a name parameter before specifying the strategy.

### CODE REVIEW

**Comment by clemos** [comment]
it's optional, isn't it ?

**Comment by fantoine** [comment]
Yes the first parameter is optional. This is why I put it on an ```@:overload``` meta.

**Comment by clemos** [comment]
Oh yeah, sorry ;) Thanks

**Comment by fantoine** [comment]
Your welcome. :)
But I just noticed I pushed that pull request to master branch instead of develop...
I don't know which one should be used for quick fixes like this?

**Comment by clemos** [comment]
Aw crap :p 
It would be better on develop, indeed :)

**Comment by fantoine** [comment]
Should I re-pull the issue?

**Comment by clemos** [comment]
Yes you need to create a new PR please (afaik)

**Pull request merged**
