### PR TITLE
Added a common overload to Express routing.

### PR DESCRIPTION
**Pull request by ciscoheat**
I see this pattern `route, middleware, middleware` a lot in documentation but it wasn't represented in the library, so here it is.

### CODE REVIEW

**Comment by clemos** [comment]
I'm in the process of "rewriting", or at least cleaning the Express externs (`dev` branch).
Also, I've introduced a `Route` abstract that unifies `Regexp` and `String` routes to reduce number of overloads, and attempt to improve error messages.
I'm actually not too much in favor of adding those signatures, as they can be expressed with `Array<Middleware>`.
A possible clean solution would be to implement variable number of arguments using macros http://haxe.org/manual/macro-rest-argument.html
So I'm afraid I won't merge this one.
What do you think ?

**Comment by clemos** [comment]
Also, these signatures are now generated using a macro, in order to add all available HTTP verbs, as documented in Express.js : https://github.com/clemos/haxe-js-kit/blob/dev/js/npm/express/Middleware.hx#L25-L88

**Comment by ciscoheat** [comment]
It's fine for me to use `Array<Middleware>` (btw, what's the difference between Middleware and MiddlewareNext?), but since I've seen the three-argument version in many Express tutorials, something like this: 

```js
app.get('/hello', isAuthenticated, function(req, res) {
    res.send('look at me!');
});
```

I was just thinking that people may expect that signature to exist if they are migrating to Haxe.

I did another push on this PR that may be more relevant. AFAIK there were some incorrect overloads for the Mongoose methods `findOne` and `findById`. Maybe I should switch to the dev branch?

**Comment by clemos** [comment]
`MiddleWareNext` just represents a `next()` callback, like in `function(req,res,next)`; it's just `?Dynamic->Void`, maybe it should be `Void->Void`, but I believe you can pass an error to it...
As for 3 arguments overloads (and generally multiple arguments overloads), as said earlier, I'm definitely not in favor of adding more signatures to "simulate" undefined number of arguments. We should either implement it properly using `macro` + [rest arguments](http://haxe.org/manual/macro-rest-argument.html), or leave it to `Array<Middleware>` or `dynamic`.
I'm also planning to eventually add stronger typing to Express, pretty much the way I did it for Mongoose, something like : 
```haxe
app.route('/item/:id')
.get( function( req, res, _ ){
  // types req to Request<{id:Int}> or something, rather than Request<Dynamic>
  // eventually inject a middleware to validate id is an int / convert id to int
  req.params.| // autocompletes id
} )
```

Regarding Mongoose (and in general), could you please work on `dev`, and make 1 PR per "feature" ?

**Comment by ciscoheat** [comment]
No problem, rest arguments would be interesting to use. I'll switch to the dev branch, but there's only one PR per branch, so I have to make a couple of feature branches. I have over 20 npm packages to be merged soon. :)

**Pull request closed without merging**
