### PR TITLE
Added dotenv package.

### PR DESCRIPTION
**Pull request by ciscoheat**
A little useful package for setting process.env variables from a file.

### CODE REVIEW

**Comment by clemos** [comment]
Thx !

**Comment by ciscoheat** [comment]
No problem. :) Since `Node.process.env` has string values only, would it make sense to return `DynamicAccess<String>` instead of `Dynamic`, or is it better that the user casts it as needed?

**Comment by clemos** [comment]
You're right, it's probably better with `DynamicAccess`, forcing the user to do more than `cast` (`parseInt`, whatever)

**Comment by ciscoheat** [comment]
Ok! I'll add to this PR then. Got some other small things as well.

**Pull request merged**
