### PR TITLE
No reason to not have more path args

### PR DESCRIPTION
**Pull request by dionjwa**

### CODE REVIEW

**Comment by clemos** [comment]
I agree with you.
But then it would be even better with `haxe.extern.Rest<String>` http://api.haxe.org/haxe/extern/Rest.html :)
Please notice that I will soon remove the core node API externs from the project, in favor of the official hxnodejs externs.

**Comment by clemos** [comment]
Have you tried with `Rest` ?

**Comment by dionjwa** [comment]
I have not yet, but I will soon.

What is your ETA for folding with the hxnodejs externs? There's some stuff in your code that is better that I'd like to see in hxnodejs, e.g. the callback typedefs (they save so much bloat).

**Comment by fullofcaffeine** [comment]
+1 on ETA for the official hxnodejs :)

**Comment by clemos** [comment]
I have no real ETA for now.
The plan is to wait for hxnodejs to be released, then dump all js.node.* definitions from haxe-js-kit.
I have currently no plan to directly contribute the hxnodejs project, if that is what you're asking, since IMHO it should only contain "official" core nodejs externs.

**Comment by clemos** [comment]
Core nodejs API have been removed, closing this issue.

**Pull request closed without merging**
