### PR TITLE
Sequelize update

### PR DESCRIPTION
**Pull request by MatthijsKamstra**
Hi Clément,

I am working on another node.js tutorial, and I made some adjustments to the Sequelize externs
because I couldn't figure out how TiagoLr wanted it to work...

The changes are probably breaking.... but there haven't been any updates for a year...

## another question
Also wanted to ask about the Promise.hx

```
	public function then(cb:Dynamic):Promise;
	@:native("catch")
	function Catch(cb:Dynamic):Promise;
	@:native("try")
	public static function Try(f:Dynamic):Promise;
	function new(f:Dynamic);
```

I get why, perhaps a beter `Catch` would be http://api.haxe.org/js/Promise.html#catchError `catchError` , but that leaves `Try`

But is there a way to "warn" javascript users (script-kiddies, first time Haxe users ) to not use `catch` but `catchError`...
Something like `@:deprecated ("don't use this, but that")`

### CODE REVIEW

**Comment by clemos** [comment]
Thanks !

Honestly, I wasn't aware of this Promise.hx file :D 
Usually, the convention in js-kit would have been `catch_` and `try_` (there is `static_`) so it works more or less well with autocomplete.
The comments say these are bluebird promises, so I think it's better to keep this convention, which lets users know it's not a "regular" promise.
What do you think ?

`catch` is a keyword in Haxe, so I think the error message if someone uses `promise.catch` will be something like `unexpected catch`, and I don't think there's a way to change that :S

**Comment by MatthijsKamstra** [comment]
Okay will change to `catch_` and `try_`

To bad about question 2... that would make Haxe Js Externs even better, just copy/paste an example and the Haxe compiler / js extern would give you advice how to "Haxify" it

**Comment by MatthijsKamstra** [comment]
I was wondering why my Sequelize tutorial failed...

**Comment by clemos** [comment]
Do you want me to merge it ?
I thought there were still open questions there.

**Comment by MatthijsKamstra** [comment]
I don't have any questions! If its okay with you could you merge

**Comment by clemos** [comment]
So be it :)

**Pull request merged**
