### PR TITLE
Sequelize tests + mongoose tests using buddy.

### PR DESCRIPTION
**Pull request by ProG4mr**
Hey, i added sequelize tests using buddy framework, after that i decided to restructure the test suite to be more consistent and easy to run or add continuous integration in the future etc.

A couple of things:

* I only ported Mongoose tests because they do not require running a server, it should be possible to port the remaining tests tho.
* `AsyncTest` suite is not filled, i couldn't figure how to create async functions myself and use them with `@async`.
* `@async` does not work inside a buddy test suite (compile-time errors). It can be used outside `describe(...) ` block tho.
* I didn't remove the original mongoose tests since they are the only example of using `@async`.
* Couple of fixes to mongoose and sequelize, including updating versions.

Can't remember of more things, see if you like it.

### CODE REVIEW

**Comment by clemos** [comment]
It's awesome that you managed to add some tests.
I'll look into this asap, as I'm very interested in implementing more (automated) tests.
Thanks a lot

**Comment by ciscoheat** [comment]
Hey @ProG4mr, nice to see you're using Buddy! (I will get started on the eachAll feature soon) 

I just made a fix for `@async` in #57, it could help with the issues you have.

**Comment by ProG4mr** [comment]
Hey, thanks, i can't figure how to test the `@async` using asynchronous methods with delays or promises.

I wrote a test suite for async callbacks, the tests are pending tho, if anyone could fill them it would provide a good source of information to learn how to use `@async` in different ways.

**Comment by ciscoheat** [comment]
That's a great idea, I can do that but after my PR #57 goes through, right now `@async` doesn't iterate through the whole AST tree, only the top level.

**Comment by clemos** [comment]
Thanks a lot :)
It would be nice to add a TravisCI configuration to have badges, automated testing and all.
I'll hopefully look into it when I have time...

**Comment by ciscoheat** [comment]
I have configured travis for a couple of multi-target projects, I can make a PR for the js target. [HaxeCI](https://github.com/andyli/HaxeCI) is a very good start for travis btw.

**Pull request merged**
