### PR TITLE
Added all packages used in the meadowlark project.

### PR DESCRIPTION
**Pull request by ciscoheat**
Hey, I'm back with a bunch of stuff. :) Everything has been tested. A few notes:

1. There are probably a few methods missing on some packages, espacially ConnectRest and Zombie.
2. Mute was so simple that I ported it to Haxe. Is this ok?

### CODE REVIEW

**Comment by clemos** [comment]
Hey!
1. is fine
2. I'm not really ok with having ported code in haxe-js-kit, so I'd prefer externs, if only for the sake of consistency

**Comment by ciscoheat** [comment]
That's fine, I only used it in a special case, so it's removed now.

**Comment by clemos** [comment]
Great work, thanks a lot !

**Comment by ciscoheat** [comment]
Glad I can help this great project. :) And thanks for the RequireNamespace<Const, Const> feature, it helped me simplify Buddy configuration a lot.

**Comment by clemos** [comment]
I didn't see `connect-mongo` is now duplicated (js.npm.ConnectMongo vs js.npm.connectmongo.MongoStore).
Also, your version depends on `express-session`, but since it's included in `__js__`, it won't be properly referenced as a dependency.
I'll have to merge / remove one of them; I think I'll keep the "standard" js.npm.ConnectMongo, but with your additions. Also, I'd like to implement it as `new ConnectMongo<js.npm.express.Session>( options )`, which would make more sense.

**Comment by ciscoheat** [comment]
Ok, no problem. Let me know when it's done and I'll update the meadowlark project.

**Comment by clemos** [comment]
It's done. The signature is now like this:
https://github.com/clemos/haxe-js-kit/blob/dev/test/ExpressTest.hx#L14

**Comment by ciscoheat** [comment]
Thanks, works just fine.

**Pull request merged**
